name: Label Enforcer

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  call-label-check:
    uses: KNMentorAGH/.github/.github/workflows/reusable-label-enforcer.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}