name: Test Runner

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-test:
    uses: KNMentorAGH/.github/.github/workflows/reusable-test.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}